apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: N8N_HOST
          value: "n8n.khalilaliouich.com"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "https"
        - name: NODE_ENV
          value: "production"
        - name: WEBHOOK_URL
          value: "https://n8n.khalilaliouich.com/"
        - name: GENERIC_TIMEZONE
          value: "Europe/Paris"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        hostPath:
          path: /var/lib/showcase/n8n-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: showcase
spec:
  selector:
    app: n8n
  ports:
  - port: 80
    targetPort: 5678
