apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: auth
data:
  configuration.yml: |
    theme: dark
    default_2fa_method: ''
    server:
      host: 0.0.0.0
      port: 9091
    log:
      level: info
    identity_providers:
      oidc:
        cors:
          endpoints:
            - authorization
            - token
            - revokation
            - introspection
            - userinfo
          allowed_origins:
            - https://grafana.khalilaliouich.com
            - https://argocd.khalilaliouich.com
            - https://git.khalilaliouich.com
          allowed_origins_from_client_redirect_uris: true
        clients:
          - id: grafana
            description: Grafana
            secret: "$${AUTHELIA_IDENTITY_PROVIDERS_OIDC_CLIENTS_GRAFANA_SECRET}"
            public: false
            authorization_policy: bypass
            redirect_uris:
              - https://grafana.khalilaliouich.com/login/generic_oauth
            scopes:
              - openid
              - profile
              - groups
              - email
            userinfo_signing_algorithm: none
          - id: argocd
            description: ArgoCD
            secret: "$${AUTHELIA_IDENTITY_PROVIDERS_OIDC_CLIENTS_ARGOCD_SECRET}"
            public: false
            authorization_policy: bypass
            redirect_uris:
              - https://argocd.khalilaliouich.com/auth/callback
            scopes:
              - openid
              - profile
              - groups
              - email
            userinfo_signing_algorithm: none
          - id: gitea
            description: Gitea
            secret: "$${AUTHELIA_IDENTITY_PROVIDERS_OIDC_CLIENTS_GITEA_SECRET}"
            public: false
            authorization_policy: bypass
            redirect_uris:
              - https://git.khalilaliouich.com/user/oauth2/authelia/callback
            scopes:
              - openid
              - profile
              - groups
              - email
            userinfo_signing_algorithm: none
    authentication_backend:
      file:
        path: /config/users_database.yml
    access_control:
      default_policy: bypass
      rules:
        - domain: auth.khalilaliouich.com
          policy: bypass
    session:
      name: authelia_session
      expiration: 3600
      inactivity: 300
      domain: khalilaliouich.com
    storage:
      local:
        path: /var/lib/authelia/db.sqlite3
    notifier:
      filesystem:
        filename: /var/lib/authelia/emails.txt

  users_database.yml: |
    users:
      admin:
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d$0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d"
        email: admin@khalilaliouich.com
        groups:
          - admins
      guest:
        displayname: "Visitor"
        password: "$argon2id$v=19$m=65536,t=3,p=4$0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d$0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d0lT9P5h6d"
        email: guest@khalilaliouich.com
        groups:
          - viewers
